jobs:
  build:
    env:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      id: vars
      name: Set outputs
      run: 'echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      env:
        MINESTOM_CHANNEL: release
        MINESTOM_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
      name: Publish to Sonatype
      run: './gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

        echo "Version: ${SHORT_COMMIT_HASH}" >> $GITHUB_STEP_SUMMARY

        '
name: Gradle Publish to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___snapshot-deploy.yaml
